apiVersion: v1
kind: Service
metadata:
  name: farmacia-web-service
spec:
  type: LoadBalancer 
  sessionAffinity: ClientIP # <--- ¡ESTA ES LA LÍNEA MÁGICA!
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: farmacia-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmacia-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: farmacia-web
  template:
    metadata:
      labels:
        app: farmacia-web
    spec:
      containers:
      - name: farmacia-web
        image: farmacia-web:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80